# Basic settings
spring.application.name=orders-service
server.port=8083

# Database configuration
spring.datasource.url=jdbc:postgresql://192.168.99.101:5434/orders_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=thisIsMySecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog.xml

integration.users-service.url=http://192.168.99.101:8081
integration.restaurants-service.url=http://192.168.99.101:8082

feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=10000
feign.client.config.default.logger-level=basic

logging.level.root=INFO
logging.level.com.fooddelivery=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.transaction=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method