# Basic settings
spring.application.name=users-service
server.port=8081

# Database configuration
spring.datasource.url=jdbc:postgresql://192.168.99.101:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml

# Swagger documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
jwt.secret=thisIsMySecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.refreshExpirationMs=86400000
jwt.expiration=3600000

logging.level.root=INFO
logging.level.com.fooddelivery=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.transaction=DEBUG

logging.level.org.springframework.security=DEBUG
logging.level.com.fooddelivery.users.security=DEBUG
logging.level.com.fooddelivery.users.config=DEBUG
logging.level.org.springframework.security.access=DEBUG
logging.level.org.springframework.security.access.intercept.aopalliance=DEBUG